on:
  issues:
    types: [assigned]

# Create a new branch (see issue-branch.yml for config) for every single assigned issue.

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
      steps:
        - name: Create Issue Branch
          uses: robvanderleek/create-issue-branch@v1.4
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
